export { default as HomePage } from './HomePage'
export { default as CatalogPage } from './CatalogPage'
export { default as ProductPage } from './ProductPage'
export { CartPage, OrdersPage, ProfilePage } from './CartPage'
export { default as AIStilPage } from './AIStilPage'
export { default as FavoritesPage } from './FavoritesPage'
export { default as PaymentPage } from './PaymentPage'
export { default as CheckoutSuccessPage } from './CheckoutSuccessPage'
